name: Java CI with Maven - Test and package
on: [pull_request] # Ce workflow se déclenche sur un push dans le dépôt
jobs:
  MavenRepositoryCreation:
    name: MavenRepositoryCreation
    runs-on: ubuntu-latest # OS où s'exécute le job
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Setup du JDK # Installation de la version de Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: '21'

      - name: Build avec Maven # Compilation et tests du projet
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar-Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')