name: Documentation Deployment

on:
    pull_request:
        types:
            - closed

jobs:
    documentation-deployment:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
            - name: Checkout du dépôt
              uses: actions/checkout@v4

            - name: Setup du JDK # Installation de la version de Java
              uses: actions/setup-java@v3
              with:
                distribution: corretto
                java-version: '21'
                cache: maven

            - name: Check merge status
              run: |
                  echo "The PR was merged"

            - name: Generate Documentation
              run: mvn -B javadoc::javadoc

            - name: Deploy
              run: peaceiris/actions-gh-pages@v4
